# Generated by Django 6.0.2 on 2026-02-25 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('tuberculosis', models.BooleanField(default=False)),
                ('cardiopatia', models.BooleanField(default=False)),
                ('otras_enfermedades', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesObstetricos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestas', models.PositiveIntegerField(default=0)),
                ('partos', models.PositiveIntegerField(default=0)),
                ('cesareas', models.PositiveIntegerField(default=0)),
                ('abortos', models.PositiveIntegerField(default=0)),
                ('nacidos_vivos', models.PositiveIntegerField(default=0)),
                ('nacidos_muertos', models.PositiveIntegerField(default=0)),
                ('peso_ultimo_rn', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('complicaciones_previas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuberculosis', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('cardiopatia', models.BooleanField(default=False)),
                ('nefropatia', models.BooleanField(default=False)),
                ('asma', models.BooleanField(default=False)),
                ('vih', models.BooleanField(default=False)),
                ('sifilis', models.BooleanField(default=False)),
                ('preeclampsia', models.BooleanField(default=False)),
                ('eclampsia', models.BooleanField(default=False)),
                ('cirugias_previas', models.TextField(blank=True, null=True)),
                ('otras_enfermedades', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('domicilio', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 8 y 15 dígitos.', regex='^[0-9]{8,15}$')])),
                ('raza', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(max_length=20)),
                ('escolaridad', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
