# Generated by Django 5.2.5 on 2026-01-05 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('domicilio', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('raza', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(max_length=20)),
                ('escolaridad', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
