# Generated by Django 5.2.5 on 2026-01-05 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('tuberculosis', models.BooleanField(default=False)),
                ('cardiopatia', models.BooleanField(default=False)),
                ('otras_enfermedades', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_familiares', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesObstetricos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestas', models.PositiveIntegerField(default=0)),
                ('partos', models.PositiveIntegerField(default=0)),
                ('cesareas', models.PositiveIntegerField(default=0)),
                ('abortos', models.PositiveIntegerField(default=0)),
                ('nacidos_vivos', models.PositiveIntegerField(default=0)),
                ('nacidos_muertos', models.PositiveIntegerField(default=0)),
                ('peso_ultimo_rn', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('complicaciones_previas', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_obstetricos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuberculosis', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('cardiopatia', models.BooleanField(default=False)),
                ('nefropatia', models.BooleanField(default=False)),
                ('asma', models.BooleanField(default=False)),
                ('vih', models.BooleanField(default=False)),
                ('sifilis', models.BooleanField(default=False)),
                ('preeclampsia', models.BooleanField(default=False)),
                ('eclampsia', models.BooleanField(default=False)),
                ('cirugias_previas', models.TextField(blank=True, null=True)),
                ('otras_enfermedades', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_personales', to='pacientes.paciente')),
            ],
        ),
    ]
