# Generated by Django 6.0.2 on 2026-02-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_antecedentesfamiliares_antecedentesobstetricos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
    ]
