# Generated by Django 6.0.2 on 2026-02-24 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_remove_paciente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 8 dígitos numéricos.', regex='^[0-9]{8}$')]),
        ),
    ]
