# Generated by Django 6.0.2 on 2026-02-25 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 8 y 15 dígitos.', regex='^[0-9]{8,15}$')]),
        ),
    ]
