# Generated by Django 5.2.5 on 2026-01-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DOCTOR', 'Doctor'), ('ENFERMERA', 'Enfermera'), ('PACIENTE', 'Paciente')], max_length=20),
        ),
    ]
