# Generated by Django 6.0.2 on 2026-02-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('usuarios', '0006_limpiar_emails_duplicados'),
]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico'),
        ),
    ]
