# Generated by Django 6.0.2 on 2026-02-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPrenatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.PositiveIntegerField(editable=False)),
                ('fecha_consulta', models.DateField(auto_now_add=True)),
                ('semana_gestacion', models.PositiveIntegerField()),
                ('motivo_consulta', models.CharField(max_length=255)),
                ('atendida', models.BooleanField(default=False)),
                ('peso_madre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presion_sistolica', models.PositiveIntegerField()),
                ('presion_diastolica', models.PositiveIntegerField()),
                ('frecuencia_cardiaca_materna', models.PositiveIntegerField()),
                ('frecuencia_respiratoria', models.PositiveIntegerField()),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('edema', models.BooleanField(default=False)),
                ('proteinuria', models.BooleanField(default=False)),
                ('altura_uterina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia_cardiaca_fetal', models.PositiveIntegerField()),
                ('movimientos_fetales', models.BooleanField()),
                ('movimientos_disminuidos', models.BooleanField(default=False)),
                ('ausencia_movimientos', models.BooleanField(default=False)),
                ('presentacion_fetal', models.CharField(choices=[('cefálica', 'Cefálica'), ('podálica', 'Podálica'), ('transversa', 'Transversa'), ('no_determinada', 'No determinada')], default='no_determinada', max_length=50)),
                ('sintomas', models.TextField()),
                ('signos_clinicos', models.TextField()),
                ('signos_alarma', models.TextField()),
                ('diabetes_gestacional', models.BooleanField(default=False)),
                ('hipertension_gestacional', models.BooleanField(default=False)),
                ('antecedentes_patologicos', models.TextField(blank=True)),
                ('consumo_medicamentos', models.TextField(blank=True)),
                ('consumo_drogas', models.BooleanField(default=False)),
                ('calculado_por', models.CharField(choices=[('fur', 'Fecha última regla'), ('usg', 'Ultrasonido')], default='fur', max_length=10)),
                ('semanas_por_ultrasonido', models.PositiveIntegerField(blank=True, null=True)),
                ('impresion_clinica', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('tratamiento', models.TextField()),
                ('proxima_cita', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
