# Generated by Django 5.2.5 on 2026-01-10 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0005_ultrasonido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPrenatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(auto_now_add=True)),
                ('semana_gestacion', models.PositiveIntegerField()),
                ('atendida', models.BooleanField(default=True, help_text='Indica si la consulta fue atendida')),
                ('peso_madre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presion_sistolica', models.PositiveIntegerField()),
                ('presion_diastolica', models.PositiveIntegerField()),
                ('edema', models.BooleanField(default=False)),
                ('proteinuria', models.BooleanField(default=False)),
                ('altura_uterina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia_cardiaca_fetal', models.PositiveIntegerField()),
                ('movimientos_fetales', models.BooleanField()),
                ('sintomas', models.TextField()),
                ('signos_alarma', models.TextField()),
                ('impresion_clinica', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('tratamiento', models.TextField()),
                ('proxima_cita', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('embarazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_prenatales', to='expedientes.embarazo')),
                ('usuario', models.ForeignKey(help_text='Profesional de salud que realiza la consulta', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
