# Generated by Django 5.2.5 on 2026-01-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaprenatal',
            name='proxima_cita',
            field=models.DateTimeField(help_text='Fecha y hora de la próxima cita'),
        ),
    ]
