# Generated by Django 6.0.2 on 2026-02-25 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaprenatal',
            name='embarazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_prenatales', to='expedientes.embarazo'),
        ),
    ]
