# Generated by Django 5.2.5 on 2026-01-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consultaprenatal_proxima_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaprenatal',
            name='atendida',
            field=models.BooleanField(default=False, help_text='Indica si la consulta fue atendida'),
        ),
    ]
