# Generated by Django 6.0.2 on 2026-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consultaprenatal_atendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaprenatal',
            name='cefalea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='conducta_fetal',
            field=models.CharField(choices=[('normal', 'Normal'), ('hipoactivo', 'Hipoactivo'), ('hiperactivo', 'Hiperactivo')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='contracciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='dolor_abdominal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='fiebre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='frecuencia_cardiaca_materna',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='frecuencia_respiratoria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='motivo_consulta',
            field=models.CharField(blank=True, help_text='¿Por qué llegó la paciente?', max_length=255),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='no_movimientos_bebe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='numero_consulta',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='presentacion',
            field=models.CharField(choices=[('cefalica', 'Cefálica'), ('podalica', 'Podálica'), ('transversa', 'Transversa')], default='cefalica', max_length=15),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='riesgo_obstetrico',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=15),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='sangrado_vaginal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='sospecha_diabetes_gestacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='sospecha_preeclampsia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='ultima_consulta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='vision_borrosa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='zumbidos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='impresion_clinica',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='proxima_cita',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la próxima cita', null=True),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='recomendaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='signos_alarma',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='sintomas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='tratamiento',
            field=models.TextField(blank=True),
        ),
    ]
