# Generated by Django 6.0.2 on 2026-02-21 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_consultaprenatal_cefalea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='cefalea',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='conducta_fetal',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='contracciones',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='dolor_abdominal',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='fiebre',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='no_movimientos_bebe',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='numero_consulta',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='riesgo_obstetrico',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='sangrado_vaginal',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='sospecha_diabetes_gestacional',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='sospecha_preeclampsia',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='ultima_consulta',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='vision_borrosa',
        ),
        migrations.RemoveField(
            model_name='consultaprenatal',
            name='zumbidos',
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='antecedentes_patologicos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='ausencia_movimientos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='calculado_por',
            field=models.CharField(choices=[('fur', 'Fecha última regla'), ('usg', 'Ultrasonido')], default='fur', max_length=10),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='consumo_drogas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='consumo_medicamentos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='diabetes_gestacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='hipertension_gestacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='movimientos_disminuidos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='presentacion_fetal',
            field=models.CharField(choices=[('cefálica', 'Cefálica'), ('podálica', 'Podálica'), ('transversa', 'Transversa'), ('no_determinada', 'No determinada')], default='no_determinada', max_length=50),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='semanas_por_ultrasonido',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultaprenatal',
            name='signos_clinicos',
            field=models.TextField(default=False, help_text='Lo que el médico observa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='atendida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='frecuencia_cardiaca_materna',
            field=models.PositiveIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='frecuencia_respiratoria',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='impresion_clinica',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='motivo_consulta',
            field=models.CharField(help_text='¿Por qué acudió la paciente?', max_length=255),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='proxima_cita',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='recomendaciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='signos_alarma',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='sintomas',
            field=models.TextField(help_text='Lo que la paciente refiere'),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, default=36.5, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='tratamiento',
            field=models.TextField(),
        ),
    ]
