# Generated by Django 6.0.2 on 2026-02-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_remove_consultaprenatal_cefalea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaprenatal',
            name='numero_control',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='motivo_consulta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='signos_clinicos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultaprenatal',
            name='sintomas',
            field=models.TextField(),
        ),
    ]
