# Generated by Django 5.2.5 on 2026-01-10 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0005_ultrasonido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='Fecha y hora de la cita')),
                ('atendida', models.BooleanField(default=False, help_text='Indica si la cita ya fue atendida')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('embarazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='expedientes.embarazo')),
                ('usuario', models.ForeignKey(help_text='Profesional que agenda la cita', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
