# Generated by Django 6.0.2 on 2026-02-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='Fecha y hora de la cita')),
                ('atendida', models.BooleanField(default=False, help_text='Indica si la cita ya fue atendida')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
