# Generated by Django 6.0.2 on 2026-02-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embarazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima_regla', models.DateField()),
                ('peso_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('embarazo_planeado', models.BooleanField(default=True)),
                ('falla_metodo_anticonceptivo', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Activo', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hb_menor_20_sem', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hb_mayor_20_sem', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ego', models.BooleanField(default=False)),
                ('vih', models.BooleanField(default=False)),
                ('sifilis', models.BooleanField(default=False)),
                ('hierro', models.BooleanField(default=False)),
                ('acido_folico', models.BooleanField(default=False)),
                ('estreptococo_b', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ultrasonido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('semanas_gestacion', models.PositiveIntegerField()),
                ('lcn', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diametro_biparietal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('femur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('placenta', models.CharField(blank=True, max_length=100, null=True)),
                ('liquido_amniotico', models.CharField(blank=True, max_length=50, null=True)),
                ('hallazgos', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ultrasonidos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
