# Generated by Django 6.0.2 on 2026-02-25 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='embarazo',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarazos', to='expedientes.expediente'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='embarazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='expedientes.embarazo'),
        ),
        migrations.AddField(
            model_name='ultrasonido',
            name='embarazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasonidos', to='expedientes.embarazo'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='embarazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='expedientes.embarazo'),
        ),
    ]
