# Generated by Django 5.2.5 on 2026-01-05 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_vacuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hb_menor_20_sem', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hb_mayor_20_sem', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ego', models.BooleanField(default=False)),
                ('vih', models.BooleanField(default=False)),
                ('sifilis', models.BooleanField(default=False)),
                ('hierro', models.BooleanField(default=False)),
                ('acido_folico', models.BooleanField(default=False)),
                ('estreptococo_b', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('embarazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='expedientes.embarazo')),
            ],
        ),
    ]
