# Generated by Django 5.2.5 on 2026-01-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_laboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ultrasonido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('semanas_gestacion', models.PositiveIntegerField()),
                ('lcn', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diametro_biparietal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('femur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('placenta', models.CharField(blank=True, max_length=100, null=True)),
                ('liquido_amniotico', models.CharField(blank=True, max_length=50, null=True)),
                ('hallazgos', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ultrasonidos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('embarazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasonidos', to='expedientes.embarazo')),
            ],
        ),
    ]
