# Generated by Django 6.0.2 on 2026-02-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_ultrasonido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarazo',
            name='semanas_gestacion',
        ),
    ]
